packages:
  - packages/*
  - templates/*
  - create-arkstack

onlyBuiltDependencies:
  - '@swc/core'
  - '@arkstack/console'
  - argon2
  - esbuild

catalog:
  '@h3ravel/musket': ^2.2.1
  '@h3ravel/support': ^2.2.0
  '@faker-js/faker': ^10.4.0
  'dotenv': ^17.4.2