packages:
  - packages/*
  - templates/*
  - create-arkstack

onlyBuiltDependencies:
  - '@swc/core'
  - '@arkstack/console'
  - argon2
  - esbuild

catalog:
  '@h3ravel/musket': ^2.2.2
  '@h3ravel/shared': ^2.2.4
  '@h3ravel/support': ^2.2.4
  '@h3ravel/collect.js': ^5.4.0
  '@faker-js/faker': ^10.4.0
  '@arkormx/plugin-clear-router': ^0.1.54
  '@resora/plugin-clear-router': ^1.0.68
  '@kanun-hq/plugin-file': ^0.1.12
  '@kanun-hq/plugin-phone': ^0.1.8
  arkormx: ^2.11.4
  clear-router: ^2.9.2
  dotenv: ^17.4.2
  express: ^5.2.1
  h3: ^2.0.1-rc.22
  kysely: ^0.29.2
  kanun: ^1.2.0
  parasito: ^0.2.6
  pg: ^8.22.0
  resora: ^1.3.28
  tsdown: ^0.22.3
