export const filesToRemove = [
    'src/app',
    'src/app/http/controllers',
    'src/app/http/resources',
    'src/models',
    'src/app/models',
    'database',
    'src/routes/api.ts',
    'src/database',
    'src/core/database.ts',
    'src/config/filesystem.ts',
    'src/config/notifications.ts',
    'src/config/database.ts',
    'src/config/resources.ts',
    'src/config/cache.ts',
    'src/config/queue.ts',
    'prisma',
    'prisma.config.ts',
    'arkorm.config.ts',
    'arkormx.config.ts',
    'arkorm.config.js',
    'arkormx.config.js',
    'arkorm.config.mjs',
    'arkormx.config.mjs',
]

export const fullDependencies = [
    '@types/pg',
    '@prisma/client',
    '@prisma/adapter-pg',
    '@arkstack/auth',
    '@arkstack/cache',
    '@arkstack/database',
    '@arkstack/filesystem',
    '@arkstack/jobs',
    '@arkstack/notifications',
    '@arkstack/queue',
    'pg',
    'kysely',
    'prisma',
    'arkormx',
]

export const leanDependencies = [
    // '@arkstack/console-slim', Depracated
]

export const depsList: Record<string, string> = {
    '@arkstack/auth': '^0.14.22',
    '@arkstack/cache': '^0.14.22',
    '@arkstack/common': '^0.14.22',
    '@arkstack/console': '^0.14.22',
    '@arkstack/foundry': '^0.14.22',
    '@arkstack/jobs': '^0.14.22',
    // '@arkstack/console-slim': '^0.14.22', Depracated
    '@arkstack/contract': '^0.14.22',
    '@arkstack/database': '^0.14.22',
    '@arkstack/driver-express': '^0.14.22',
    '@arkstack/driver-h3': '^0.14.22',
    '@arkstack/filesystem': '^0.14.22',
    '@arkstack/http': '^0.14.22',
    '@arkstack/view': '^0.14.22',
    '@arkstack/queue': '^0.14.22',
    '@arkstack/notifications': '^0.14.22',
    '@h3ravel/musket': '^2.2.1',
    '@h3ravel/support': '^2.2.0',
}

export const environment = {
    min: [
        'PORT',
        'HOST',
        'APP_URL',
        'APP_KEY',
        'APP_ENV',
        'APP_HOST',
        'APP_PORT',
        'APP_NAME',
        'APP_DEBUG',
        'APP_LOCALE',
        'APP_TIMEZONE',
        'NODE_ENV',
        'FRONTEND_URL',
        'NGROK_DOMAIN',
        'NGROK_AUTHTOKEN',
        'APP_FAKER_LOCALE',
        'APP_FALLBACK_LOCALE'
    ],
    max: [
        'FILESYSTEM_DISK',
        'CACHE_STORE',
        'QUEUE_CONNECTION',
        'REDIS_HOST',
        'REDIS_PORT',
        'REDIS_PASSWORD',
        'JWT_EXPIRES_IN',
        'DATABASE_URL',
        'DB_CONNECTION',
        'DB_HOST',
        'DB_PORT',
        'DB_DATABASE',
        'DB_USERNAME',
        'DB_PASSWORD',
        'MAIL_HOST',
        'MAIL_PORT',
        'MAIL_SECURE',
        'MAIL_USERNAME',
        'MAIL_PASSWORD',
        'MAIL_FROM_ADDRESS',
        'MAIL_TEST_ADDRESS',
        'AWS_ACCESS_KEY_ID',
        'AWS_SECRET_ACCESS_KEY',
        'AWS_DEFAULT_REGION',
        'AWS_BUCKET',
        'AWS_URL',
        'AWS_ENDPOINT',
    ],
}